//
// Created by Victor on 07.10.2019.
//

#ifndef OURSQL_APP_LOGIC_PARSER_NODES_INTCONSTANT_H_
#define OURSQL_APP_LOGIC_PARSER_NODES_INTCONSTANT_H_

class IntConstant {};

#endif  // OURSQL_APP_LOGIC_PARSER_NODES_INTCONSTANT_H_
