//
// Created by Victor on 07.10.2019.
//

#ifndef OURSQL_APP_LOGIC_PARSER_NODES_REALCONSTANT_H_
#define OURSQL_APP_LOGIC_PARSER_NODES_REALCONSTANT_H_

class RealConstant {};

#endif  // OURSQL_APP_LOGIC_PARSER_NODES_REALCONSTANT_H_
