//
// Created by Victor on 07.10.2019.
//

#ifndef OURSQL_APP_LOGIC_PARSER_NODES_TEXTCONSTANT_H_
#define OURSQL_APP_LOGIC_PARSER_NODES_TEXTCONSTANT_H_

class TextConstant {};

#endif  // OURSQL_APP_LOGIC_PARSER_NODES_TEXTCONSTANT_H_
