name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GCC
      run: sudo apt-get install -y gcc g++
    - name: Install CMake
      run: wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz && tar -zxvf cmake-3.15.2.tar.gz && cd cmake-3.15.2 && ./bootstrap && make && sudo make install
    - name: Install Boost
      run: sudo apt-get install libboost-all-dev
    - name: test
      run: cmake .
